language: go
go:
  - "1.10"
  - tip
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
install: go get -v .
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
